SET IDENTITY_INSERT [dbo].[Salarii] ON
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (3, N'Vera      ', N'Veronica  ', N'2,500     ', N'-         ', N'-', CAST(6120801016709 AS Decimal(18, 0)))
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (4, N'Popescu   ', N'Cristina  ', N'2,500     ', N'-         ', N'-', CAST(6120802018588 AS Decimal(18, 0)))
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (8, N'Negru     ', N'Maria     ', N'2,500     ', N'-         ', N'-         ', CAST(6120817359321 AS Decimal(18, 0)))
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (9, N'Iorga     ', N'Elena     ', N'2,500     ', N'-         ', N'-         ', CAST(6030809356000 AS Decimal(18, 0)))
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (10, N'Popa      ', N'Ionuț     ', N'2,500     ', N'-         ', N'-         ', CAST(5011123356694 AS Decimal(18, 0)))
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (11, N'Gherghe   ', N'Emilian   ', N'2,500     ', N'-         ', N'-         ', CAST(5011111359664 AS Decimal(18, 0)))
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (12, N'Caragea   ', N'Anda      ', N'2,500     ', N'-         ', N'-         ', CAST(6010817358630 AS Decimal(18, 0)))
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (13, N'Bre       ', N'Andra     ', N'2,500     ', N'-         ', N'-         ', CAST(2960612356207 AS Decimal(18, 0)))
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (14, N'Jones     ', N'Jack      ', N'2,500     ', N'-         ', N'-         ', CAST(1991116357838 AS Decimal(18, 0)))
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (15, N'Lombaro   ', N'Joey      ', N'2,500     ', N'-         ', N'-         ', CAST(5030611359449 AS Decimal(18, 0)))
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (16, N'Fugaciu   ', N'Adelina   ', N'2,500     ', N'-         ', N'-         ', CAST(2920624357645 AS Decimal(18, 0)))
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (17, N'Varvare   ', N'Larisa    ', N'2,500     ', N'-         ', N'-         ', CAST(6010614359493 AS Decimal(18, 0)))
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (18, N'Costas    ', N'Viviana   ', N'2,500     ', N'-         ', N'-         ', CAST(6061109359815 AS Decimal(18, 0)))
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (19, N'Ivănescu  ', N'Irina     ', N'2,500     ', N'-         ', N'-         ', CAST(6060411359130 AS Decimal(18, 0)))
INSERT INTO [dbo].[Salarii] ([Id], [Nume], [Prenume], [Salariu], [Bonus], [Explicatii], [CNP]) VALUES (20, N'Matei     ', N'Ionela    ', N'2,500     ', N'-         ', N'-         ', CAST(6011121356260 AS Decimal(18, 0)))
SET IDENTITY_INSERT [dbo].[Salarii] OFF
